version: '3.9'
services:
  vscode-devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    command: sleep infinity
    restart: never
    environment:
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ./
        target: "/workspaces/${COMPOSE_PROJECT_NAME}"
        consistency: delegated
    networks:
      vscode-back-net-dev:
      vscode-db-net-dev:
networks:
  vscode-back-net-dev: {}
  vscode-db-net-dev: {}
